# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{orange}
  s.version = "0.0.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Haslem"]
  s.date = %q{2010-02-17}
  s.description = %q{Orange is a Ruby framework for building managed websites with code as simple as Sinatra}
  s.email = %q{therabidbanana@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "lib/orange.rb",
     "lib/orange/application.rb",
     "lib/orange/carton.rb",
     "lib/orange/cartons/asset_carton.rb",
     "lib/orange/cartons/page_carton.rb",
     "lib/orange/cartons/page_version_carton.rb",
     "lib/orange/cartons/site_carton.rb",
     "lib/orange/cartons/user_carton.rb",
     "lib/orange/core.rb",
     "lib/orange/magick.rb",
     "lib/orange/middleware/access_control.rb",
     "lib/orange/middleware/base.rb",
     "lib/orange/middleware/database.rb",
     "lib/orange/middleware/flex_router.rb",
     "lib/orange/middleware/four_oh_four.rb",
     "lib/orange/middleware/globals.rb",
     "lib/orange/middleware/loader.rb",
     "lib/orange/middleware/radius_parser.rb",
     "lib/orange/middleware/rerouter.rb",
     "lib/orange/middleware/restful_router.rb",
     "lib/orange/middleware/route_context.rb",
     "lib/orange/middleware/route_site.rb",
     "lib/orange/middleware/show_exceptions.rb",
     "lib/orange/middleware/site_load.rb",
     "lib/orange/middleware/static.rb",
     "lib/orange/middleware/static_file.rb",
     "lib/orange/middleware/template.rb",
     "lib/orange/packet.rb",
     "lib/orange/resource.rb",
     "lib/orange/resources/admin_resource.rb",
     "lib/orange/resources/asset_resource.rb",
     "lib/orange/resources/mapper.rb",
     "lib/orange/resources/model_resource.rb",
     "lib/orange/resources/not_found.rb",
     "lib/orange/resources/page_parts.rb",
     "lib/orange/resources/page_resource.rb",
     "lib/orange/resources/parser.rb",
     "lib/orange/resources/radius.rb",
     "lib/orange/resources/routable_resource.rb",
     "lib/orange/resources/singleton_model_resource.rb",
     "lib/orange/resources/sitemap_resource.rb",
     "lib/orange/resources/slices.rb",
     "lib/orange/resources/user_resource.rb",
     "lib/orange/stack.rb"
  ]
  s.homepage = %q{http://github.com/therabidbanana/orange}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Middle ground between Sinatra and Rails}
  s.test_files = [
    "spec/orange/application_spec.rb",
     "spec/orange/carton_spec.rb",
     "spec/orange/core_spec.rb",
     "spec/orange/magick_spec.rb",
     "spec/orange/middleware/access_control_spec.rb",
     "spec/orange/middleware/base_spec.rb",
     "spec/orange/middleware/database_spec.rb",
     "spec/orange/middleware/globals_spec.rb",
     "spec/orange/middleware/rerouter_spec.rb",
     "spec/orange/middleware/restful_router_spec.rb",
     "spec/orange/middleware/route_context_spec.rb",
     "spec/orange/middleware/route_site_spec.rb",
     "spec/orange/middleware/show_exceptions_spec.rb",
     "spec/orange/middleware/site_load_spec.rb",
     "spec/orange/middleware/static_file_spec.rb",
     "spec/orange/middleware/static_spec.rb",
     "spec/orange/middleware/template_spec.rb",
     "spec/orange/mock/mock_app.rb",
     "spec/orange/mock/mock_carton.rb",
     "spec/orange/mock/mock_core.rb",
     "spec/orange/mock/mock_middleware.rb",
     "spec/orange/mock/mock_mixins.rb",
     "spec/orange/mock/mock_model_resource.rb",
     "spec/orange/mock/mock_pulp.rb",
     "spec/orange/mock/mock_resource.rb",
     "spec/orange/mock/mock_router.rb",
     "spec/orange/orange_spec.rb",
     "spec/orange/packet_spec.rb",
     "spec/orange/resource_spec.rb",
     "spec/orange/resources/admin_resource_spec.rb",
     "spec/orange/resources/mapper_spec.rb",
     "spec/orange/resources/model_resource_spec.rb",
     "spec/orange/resources/parser_spec.rb",
     "spec/orange/resources/routable_resource_spec.rb",
     "spec/orange/resources/singleton_model_resource_spec.rb",
     "spec/orange/resources/sitemap_resource_spec.rb",
     "spec/orange/spec_helper.rb",
     "spec/orange/stack_spec.rb",
     "spec/stats.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, [">= 0.10.2"])
      s.add_runtime_dependency(%q<dm-more>, [">= 0.10.2"])
      s.add_runtime_dependency(%q<rack>, [">= 1.0.1"])
      s.add_runtime_dependency(%q<haml>, [">= 2.2.13"])
      s.add_runtime_dependency(%q<rack-abstract-format>, [">= 0.9.9"])
      s.add_runtime_dependency(%q<rack-openid>, [">= 0.2.2"])
      s.add_runtime_dependency(%q<openid_dm_store>, [">= 0.1.3"])
      s.add_runtime_dependency(%q<dm-is-awesome_set>, [">= 0.11.0"])
      s.add_runtime_dependency(%q<radius>, [">= 0.6.1"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
    else
      s.add_dependency(%q<dm-core>, [">= 0.10.2"])
      s.add_dependency(%q<dm-more>, [">= 0.10.2"])
      s.add_dependency(%q<rack>, [">= 1.0.1"])
      s.add_dependency(%q<haml>, [">= 2.2.13"])
      s.add_dependency(%q<rack-abstract-format>, [">= 0.9.9"])
      s.add_dependency(%q<rack-openid>, [">= 0.2.2"])
      s.add_dependency(%q<openid_dm_store>, [">= 0.1.3"])
      s.add_dependency(%q<dm-is-awesome_set>, [">= 0.11.0"])
      s.add_dependency(%q<radius>, [">= 0.6.1"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
    end
  else
    s.add_dependency(%q<dm-core>, [">= 0.10.2"])
    s.add_dependency(%q<dm-more>, [">= 0.10.2"])
    s.add_dependency(%q<rack>, [">= 1.0.1"])
    s.add_dependency(%q<haml>, [">= 2.2.13"])
    s.add_dependency(%q<rack-abstract-format>, [">= 0.9.9"])
    s.add_dependency(%q<rack-openid>, [">= 0.2.2"])
    s.add_dependency(%q<openid_dm_store>, [">= 0.1.3"])
    s.add_dependency(%q<dm-is-awesome_set>, [">= 0.11.0"])
    s.add_dependency(%q<radius>, [">= 0.6.1"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
  end
end

